# Generated by Django 2.1.7 on 2019-05-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=1000)),
                ('rank', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
