# Generated by Django 2.1.7 on 2019-06-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmap', '0002_auto_20190525_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='area_g',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='area_j',
            field=models.IntegerField(default=0),
        ),
    ]
